
package:
  name: pygslib
  version: "0.0.0.4.0.0"

python:
  - 3.6

requirements:
  build:
    - python
    - cython
    - setuptools
    - numpy
    - vc=14.1
    - vs2015_runtime
    - libpython

  run:
    - python
    - numpy
    - pandas >=0.17
    - matplotlib
    - scipy
    - vtk  >=7.1
    - ipython
    - colour
    - bokeh
    - ezdxf

about:
  home: https://github.com/opengeostat/pygslib
  license: MIT License
  summary: 'Python wrap of GSLIB modified code and general geostatistical package'
